env: dev

http:
  host: localhost
  port: 8088
  timeout: 5s

sizes:
  - {name: thumbnail, width: 150, height: 150}
  - {name: medium, width: 800, height: 600}

worker_num: 4
storage:
  upload_dir: "./storage/images/uploads"
  processed_dir: "./storage/images/processed"